### ISSUE TITLE
gr-lora encoder branch installation issues on Ubuntu 20.04

### ISSUE THREAD

**Issue by ph03n1xAu** [rpp0/gr-lora#134]
Hello,

I am having some problem with the encoder branch. I guess I installed everything properly but when I tried to run the grc, I'm getting error regarding swig library. 
Please note that, I installed the master branch in the same linux distribution with swig4.0. Lora-Receiver with decoding working 100%  without any problem. I want to test the transmitter now from the encoder branch

This is the error

`Traceback (most recent call last):
  File "./lora_receive_realtime.py", line 34, in <module>
    import lora
  File "/usr/lib/python3/dist-packages/lora/__init__.py", line 28, in <module>
    from .lora_swig import *
  File "/usr/lib/python3/dist-packages/lora/lora_swig.py", line 13, in <module>
    from . import _lora_swig
**ImportError: /usr/lib/python3/dist-packages/lora/_lora_swig.so: undefined symbol: _ZN2gr4lora7encoder4makeEv**
`

And this is the grc flow after installing encoder branch, same as apps/lora_receive_realtime.grc replacing the hardware source only. 

![image](https://user-images.githubusercontent.com/56659652/110572553-c4710a80-81ad-11eb-8bf3-658325db0944.png)

These are the commands for installation:

_git clone --branch encoder https://github.com/rpp0/gr-lora.git
cd gr-lora/
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr ../
make
sudo make install
sudo ldconfig_

Swig Version:
_$ swig -version
SWIG Version 4.0.1
Compiled with g++ [x86_64-pc-linux-gnu]
Configured options: +pcre_

Additionally, I tried with cmake ../ without any DCMAKE options. This time around, I got different error while running realtime.grc file

`Traceback (most recent call last):
  File "./lora_receive_realtime.py", line 250, in <module>
    main()
  File "./lora_receive_realtime.py", line 228, in main
    tb = top_block_cls()
  File "./lora_receive_realtime.py", line 125, in __init__
    self.lora_lora_receiver_0 = lora.lora_receiver(1e6, capture_freq, [target_freq], bw, sf, False, 4, True, False, False, decimation, False, False)
**AttributeError: module 'lora' has no attribute 'lora_receiver'**
`

Am I missing some libraries in encoder branch compilation which are different than the master branch?

Any suggestions are welcome !

**Comment by ph03n1xAu** [comment]
Older version of swig library was messing up during the installation process.
Problem Solved after fresh ubuntu/gnuradio installation.
