### ISSUE TITLE
AttributeError: 'module' object has no attribute 'message_socket_sink'

### ISSUE THREAD

**Issue by morganrallen** [rpp0/gr-lora#72]
After much tinkering I finally got this to somewhat work, but only inside the docker environment.
When running from my Ubuntu system I get the following.
```
Traceback (most recent call last):
  File "apps/lora_receive_realtime.py", line 173, in <module>
    main()
  File "apps/lora_receive_realtime.py", line 167, in main
    tb = top_block_cls()
  File "apps/lora_receive_realtime.py", line 87, in __init__
    self.lora_message_socket_sink_0 = lora.message_socket_sink('127.0.0.1', 40868, 0)
AttributeError: 'module' object has no attribute 'message_socket_sink'
```

This is after following the build instructions in the main readme.

**Comment by morganrallen** [comment]
I also am seeing another variation of this.
```
Traceback (most recent call last):
  File "./lora_receive_realtime.py", line 171, in <module>
    main()
  File "./lora_receive_realtime.py", line 165, in main
    tb = top_block_cls()
  File "./lora_receive_realtime.py", line 87, in __init__
    self.lora_lora_receiver_0 = lora.lora_receiver(1e6, capture_freq, ([target_freq]), sf, 1000000, 0.01)
  File "/usr/local/lib/python2.7/dist-packages/lora/lora_receiver.py", line 43, in __init__
    self.channelizer = lora.channelizer(in_samp_rate, out_samp_rate, center_freq, channel_list)
AttributeError: 'module' object has no attribute 'channelizer'
```

**Comment by morganrallen** [comment]
Seems was due to not having SWIG installed.
